// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmNkR6m0Bqh5zQ9o3mzrOwkIdQSpqZZzU',
    appId: '1:805970283049:web:685d25ae8df8e04074aa38',
    messagingSenderId: '805970283049',
    projectId: 'spendwise-9f02b',
    authDomain: 'spendwise-9f02b.firebaseapp.com',
    databaseURL: 'https://spendwise-9f02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendwise-9f02b.firebasestorage.app',
    measurementId: 'G-SM8LLFE3FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZaw_WqyNg28Kir4yDw0hwwIPJ2BjGx74',
    appId: '1:805970283049:android:ec5dd3fce8657bf474aa38',
    messagingSenderId: '805970283049',
    projectId: 'spendwise-9f02b',
    databaseURL: 'https://spendwise-9f02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendwise-9f02b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOoxOYiQ1ApFsH8V4AYGKHLPOPWUPrO8',
    appId: '1:805970283049:ios:5a3f8c94d226a38874aa38',
    messagingSenderId: '805970283049',
    projectId: 'spendwise-9f02b',
    databaseURL: 'https://spendwise-9f02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendwise-9f02b.firebasestorage.app',
    iosBundleId: 'com.example.spendwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxOoxOYiQ1ApFsH8V4AYGKHLPOPWUPrO8',
    appId: '1:805970283049:ios:5a3f8c94d226a38874aa38',
    messagingSenderId: '805970283049',
    projectId: 'spendwise-9f02b',
    databaseURL: 'https://spendwise-9f02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendwise-9f02b.firebasestorage.app',
    iosBundleId: 'com.example.spendwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmNkR6m0Bqh5zQ9o3mzrOwkIdQSpqZZzU',
    appId: '1:805970283049:web:36c0460f8900f2f674aa38',
    messagingSenderId: '805970283049',
    projectId: 'spendwise-9f02b',
    authDomain: 'spendwise-9f02b.firebaseapp.com',
    databaseURL: 'https://spendwise-9f02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendwise-9f02b.firebasestorage.app',
    measurementId: 'G-GMV75E1RGS',
  );

}